name: Cache Example

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache step
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/dependencies
          key: cache-17e3297

      - name: prime-cache-17e3297
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"

